# Makefile for numberGen.c

# Compiler and flags
CC = gcc
CFLAGS = -Wall -Wextra -Werror -O2 -std=c11

all:
	$(CC) $(CFLAGS) -o numberGen numberGen.c

clean:
	rm -f numberGen numberGen.o numbers.txt

